---
session_store_driver: InMemory
ownership_voucher_store_driver: Directory
ownership_voucher_store_config: /home/fido-user/ownership_vouchers/
trusted_device_keys_path: /home/fido-user/keys/device_ca_cert.pem
owner_private_key_path: /home/fido-user/keys/owner_key.der
bind: 0.0.0.0:8080
service_info:
  rhsm_organization_id: 6454383
  rhsm_activation_key: SDOkey
  rhsm_run_insights: true
  sshkey_user: root
  sshkey_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/sAUTiUPzFzvF07+xERRcRZ//PbrfA199uR9LwkOKTAh9uvd043kLb7KwTP/rJMAv4IMGUTeDo9rCaOz4SDVjeZShPXACEPsyEmGC0MNw5FiY6+9HLIgJyMyKUvA2PktwRA4LTHJnoBvV4Fcen+eCpccE2FDc1S0PcCJvKgBTfNbR8lqOfyOZnvTWwW0j6zh6m/u8z1P4tRiPCbjWLA78Flx0HPfh58Xqoi04R+um2lIWBCfFZJDJnnxiZlPGl/MWy2yJHi2iMfsmX03EMRVuszX0JhruXc6kpV7GxFJMRdXDBjRYher45Clge0S95gweNMgS1hFyL3H2fZoYPYWkAh3jGofyjCUyWut4JCp16WLO5bWGL5SvxRnICeApe/sVKQ+z/x2wtMkDYaGBBWLesbfoKyx8cuSyUWRsv324ouVVVMbVqfcUyIthRcjcZUkb/wwluauTanNGMDchw9pMrsBlyDrAG4u2oYb3+k+5YowEtMU5OhDtxDi3lHPkhFgrORx9sjcQIEBvOPtmluMAPRF6Ej8mjSvLKzgqhiU5s1tgm2iLHMg9PKvMGK3doW7Xtr/UtP4vNJpmd2VEZeND8NFJWvqPAfw6vNTA9NYrMDJ9qeI5NQRHdL9rOCvCeSX6v0OCVD0wemsK+eK8bY35NTmeW/uI2NxDHG1dewynYQ== ayosef@redhat.com"
